title: "Islamic Passport"
subtitle: "Sistema de Identificação e Autenticação de Mulçumanos e Entidades Islamicas"
description: >-
  Plataforma oficial de identificação e autenticação para a comunidade islâmica global,
  promovendo conexões seguras entre fiéis e entidades reconhecidas.
keywords:
  - "Islamic Passport"
  - "identidade digital islâmica"
  - "blockchain islâmico"
  - "confiança mútua"
  - "ética islâmica"
social_image: "/imgs/logo-mark-square-512.png"
robots: "index,follow"
url: ""
baseurl: ""
permalink: pretty
lang: pt-BR
timezone: America/Fortaleza
atom_feed:
  path: atom.xml
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed
collections:
  news:
    output: true
    permalink: /news/:name/
  releases:
    output: true
    permalink: /releases/:name/
  entities:
    output: true
    permalink: /entities/:name/
  staff:
    output: true
    permalink: /staff/:name/
defaults:
  - scope:
      path: ""
    values:
      image: "/imgs/logo-mark-square-512.png"
      og_type: "website"
      twitter_card: "summary_large_image"
  - scope:
      path: ""
      type: "news"
    values:
      layout: item
      section_title: "Notícias"
      og_type: "article"
  - scope:
      path: ""
      type: "releases"
    values:
      layout: item
      section_title: "Lançamentos"
      og_type: "article"
  - scope:
      path: ""
      type: "entities"
    values:
      layout: item
      section_title: "Entidades"
      og_type: "article"
  - scope:
      path: ""
      type: "staff"
    values:
      layout: author
      section_title: "Equipe"
      og_type: "profile"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

feed:
  path: feed.xml

sitemap:
  filename: sitemap.xml
  exclude:
    - gemfiles
    - node_modules

paginate: 7
paginate_path: "/page/:num"

exclude: ["_site", "Gemfile", "Gemfile.lock", "node_modules", ".gitignore", ".github"]